name: Release CI
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  create_draft:
    name: Create Draft Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate changelog
        id: change_log
        run: |
          version=$(echo $RELEASE_VERSION | sed 's/^v//g')
          changes=$(python3 generate_changelog.py -v $version)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          echo "::set-output name=changes::$changes"
          echo "::set-output name=version::$version"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: FlashPay JS SDK ${{ env.RELEASE_VERSION }} -
          body: |
            # Description
            For more information check the detailed changelog below :point_down:
            ${{ steps.change_log.outputs.changes }}
          draft: true

  build_packages:
    name: Add packages to release
    runs-on: ubuntu-latest
    needs: create_draft
    steps:
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Build packages
        run: npm ci && npm run build

      - name: Upload to draft release
        uses: rotki/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: FlashPay JS SDK ${{ env.RELEASE_VERSION }} -
          draft: true
          files: |
            dist/*

  npm_publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build_packages
    steps:
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@flashpay-inc'

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm ci && npm publish